#!/usr/bin/env bash

## Kill if already running
killall -9 xfsettingsd picom polybar mpd dunst ksuperkey xfce4-power-manager

## Restore Wallpaper
nitrogen --restore

## xfce4-settings daemon
xfsettingsd &

## polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

## Enable power management
xfce4-power-manager &

## Start Compositing Manager
exec picom &

## Notification Daemon
exec dunst &

## Start Music Player Daemon
mpd &

## Launch
xrdb -load /.Xresources &
sxhkd &
tint2 &
sh ~/.conky/Cpu/start.sh &
